let suggestions = [
    "FOOD & RESTAURANTS",
    "Clubs & Tarven",
    "plumbing",
    "Saloon",
    "TuckShop",
    "Shisanyama",
    "Catering",
    "BarberShop",
    "Funeral cover",
    "Car Sale",
    "Car For Rent",
    "Freelancer",
    "herbalist",
    "School",
    "Art & Drama ",
    "Web Designer",
    "Studio",
    "Lawyer",
    "Repaires",
    "Consultant",
    "Garage And Doors",
    "Removal Storage",
    "Fitness Clubs, Gyms & Personal Trainers",
    "Doctors & Surgeries",
    "Medical Aid Schemes & Medical Centre",
    "Dstv",
    "PreSchools",
    "Clubs",
    "Garages",
    "Resturants",
];
